#!/bin/bash

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

# default dir is .
(( $# == 0 )) && set -- '.'

for dir; do
  [[ ! -d $dir ]]  && echo "$dir is not a directory, skipping" >&2 && continue
  # firstly remove src and pkg directory to avoid find to go through
  find "$dir" -type d -a '(' -name 'src' -o -name 'pkg' ')' | while read -r d; do
    base=$(dirname "$d")
    [[ -r "$base/PKGBUILD" ]] && echo "$d" && 'rm' -r "$d"
  done

  find "$dir" \( \
            -name '*.pkg.tar.xz' \
         -o -name '*.pkg.tar.xz.sig' \
         -o -name '*.pkg.tar.zst' \
         -o -name '*.pkg.tar.zst.sig' \
         -o -name '*.src.tar.gz' \
         -o -name '*.log' \
         -o -name 'svn-commit.tmp' \
         \) -delete -print
done

# vim:set ts=2 sw=2 ft=sh et:
