#!/bin/bash

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

AUR_URL='https://aur.archlinux.org/cgit/aur.git/snapshot'

(( $# < 1 )) && echo "usage: ${0##*/} <pkgsource> [pkgsource]..." >&2 && exit 1

umask 0022

for pkg; do
  [[ -e "$pkg.tar.gz" ]] && echo "$pkg.tar.gz already exists. skipped!" >&2 && continue
	wget "$AUR_URL/$pkg.tar.gz" || continue
  tar -xvv --no-same-owner --no-same-permissions -f "$pkg.tar.gz"
  (( $UID == 0 )) && chown -R nobody:nobody "$pkg"
done

# vim:set ts=2 sw=2 ft=sh et:
