#!/bin/bash

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

# Easy kexec

shopt -s nullglob

type -P kexec >/dev/null || { echo "kexec is not in PATH" >&2; exit 1; }
[[ -r /boot ]] || { echo "Unable to read /boot" >&2; exit 1; }

select kernel in /boot/vmlinuz-*; do
	if [[ -e /boot/initramfs-${kernel##*vmlinuz-}.img ]]; then
		initrd="--initrd /boot/initramfs-${kernel##*vmlinuz-}.img"
	fi
	kexec -l --reuse-cmdline $initrd "$kernel"
	systemctl kexec
	break
done
